### ISSUE TITLE
I can't find "\\logclass_bgl_2310136305\\best_params.json" where did it come from?

### ISSUE THREAD

**Issue by refuserMa** [NetManAIOps/LogClass#3]
When I try to run the code without --train,it comes to an error:
python -m LogClass.logclass  --force --kfold 3 --logs_type "bgl" --logs "LogClass/output/preprocessed_logs/bgl.txt" --models_dir "F:\Users\Desktop\LogClass\LogClass\output\logclass_bgl_4117346017\models" --featu
res_dir "F:\Users\Desktop\LogClass\LogClass\output\logclass_bgl_4117346017\features" --report macro
---------------------------------------------------------------------------------------------------------------------------------------------
Experiment ID: 2310136305
F:\Users\Desktop\LogClass\LogClass\output\logclass_bgl_2310136305
Traceback (most recent call last):
  File "D:\ANACONDA\envs\study\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ANACONDA\envs\study\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Users\Desktop\LogClass\LogClass\logclass.py", line 201, in <module>
    main()
  File "F:\Users\Desktop\LogClass\LogClass\logclass.py", line 185, in main
    load_params(params)
  File "F:\Users\Desktop\LogClass\LogClass\utils.py", line 28, in load_params
    with open(params_file, "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Users\\Desktop\\LogClass\\LogClass\\output\\logclass_bgl_2310136305\\best_params.json'

--------------------------------------------------------------------------------------------------------------------------------------------
I have had several best_pararms.json of different outputs,but every time I run this code above,it can give me best_pararms.json of different id which can't found.
Is there anything wrong with the code?

**Comment by federicozaiter** [comment]
In this case you would also need to specify the previous experiment's id with --id .  This id is automatically generated if not specified, so in your example it seems it's trying to retrieve the best params from the current experiment which didn't save any best_params.

**Comment by jiansuanli** [comment]
> 
Whether this issue is solved, I have also encountered the same problem and look forward to your reply

**Comment by refuserMa** [comment]
I haven't solved this problem , this file maybe come from&nbsp;previous paper , or other data set.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NetManAIOps/LogClass"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NetManAIOps/LogClass] I can't find "\\logclass_bgl_2310136305\\best_params.json" where did it come from? (#3)





   
Whether this issue is solved, I have also encountered the same problem and look forward to your reply

**Comment by federicozaiter** [comment]
You need to specify the `id` of the previous experiment you ran to retrieve its best parameters. I've now added a warning that explains this issue when running inference without manually setting an experiment id. 

@refuserMa, it seems that in your case you need to run it in the following way, note I'm adding the experiment id 4117346017 to the command you shared above:
```
python -m LogClass.logclass --id 4117346017  --force --kfold 3 --logs_type "bgl" --logs "LogClass/output/preprocessed_logs/bgl.txt" --models_dir "F:\Users\Desktop\LogClass\LogClass\output\logclass_bgl_4117346017\models" --featu
res_dir "F:\Users\Desktop\LogClass\LogClass\output\logclass_bgl_4117346017\features" --report macro
```
Please let me know if this works now. Thanks!
